apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
      push: false
  artifacts:
    - image: zencles/multi-client
      context: client
      sync:
        infer:
        - '**/*.js'
        - '**/*.css'
        - '**/*.html'
      docker:
        dockerfile: Dockerfile.dev
    - image: zencles/multi-server
      context: server
      sync:
        infer:
        - '**/*.js'
      docker:
        dockerfile: Dockerfile.dev
    - image: zencles/multi-worker
      context: worker
      sync:
        infer:
          - '**/*.js'
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml
      - k8s/server-deployment.yml
      - k8s/worker-deployment.yml
      - k8s/server-cluster-ip-service.yml